/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'MarkPerry' at '2/08/15 9:40 AM' with Gradle 2.4
 *
 * @author MarkPerry, @date 2/08/15 9:40 AM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
