/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'MarkPerry' at '2/08/15 9:40 AM' with Gradle 2.4
 *
 * @author MarkPerry, @date 2/08/15 9:40 AM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
